import { StyleSheet } from 'react-native';
import { colors } from '../../../stylesGlobal';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentContainer: {
    alignItems: 'center',
    paddingBottom: 28,
  },
  header: {
    width: '100%',
    backgroundColor: colors.primary,
    borderRadius: 15,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 20,
    marginTop: 30,
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 4,
  },
  titulo: {
    fontSize: 26,
    fontWeight: '700',
    color: colors.primaryDark,
    marginTop: 50,
    textAlign: 'center',
  },
  tituloProj: {
    fontSize: 26,
    fontWeight: '700',
    color: colors.surface,
    marginBottom: 10,
    marginTop: 0,
    textAlign: 'center',
  },
  input: {
    width: '100%',
    height: 52,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 0,
    fontSize: 15,
    color: colors.text,
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  projetosSection: {
    width: '100%',
    maxWidth: 360,
    paddingHorizontal: 24,
  },
  projetosContainer: {
    width: '100%',
    gap: 12,
    marginTop: 20,
  },
  projetoCard: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  projetoTitulo: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  projetoDescricao: {
    color: colors.mutedText,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 10,
  },
  projetoStatusContainer: {
    marginTop: 12,
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  projetoStatus: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
  },
  projetoStatusAberto: {
    backgroundColor: '#22c55e',
  },
  projetoStatusEmAndamento: {
    backgroundColor: '#f59e0b',
  },
  projetoStatusFinalizado: {
    backgroundColor: '#6366f1',
  },
  loadingContainer: {
    marginTop: 28,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
  },
  loadingText: {
    marginTop: 12,
    color: colors.mutedText,
    fontSize: 14,
  },
  emptyState: {
    marginTop: 24,
    padding: 18,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primaryDark,
    marginBottom: 6,
  },
  emptyText: {
    color: colors.mutedText,
    fontSize: 14,
    textAlign: 'center',
  },
});
