import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: { flex: 1 },
  titleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 18,
    paddingHorizontal: 20,
  },
  projectTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '700',
    marginRight: 10,
  },
  createButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
  },
  createButtonText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  disabledButton: { opacity: 0.55 },
  formModalCard: { maxHeight: '90%' },
  formScroll: { flexShrink: 1 },
  formLabel: { fontSize: 14, fontWeight: '700', marginTop: 12 },
  formError: { fontSize: 13, marginTop: 8 },
  formInput: {
    borderRadius: 8,
    borderWidth: 1,
    fontSize: 16,
    marginTop: 7,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  optionButton: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    flexGrow: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  formActions: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 16,
  },
  formActionButton: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    minWidth: 95,
    paddingHorizontal: 14,
  },
  board: {
    gap: 12,
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  boardScroll: { flex: 1 },
  column: {
    borderRadius: 12,
    borderWidth: 1,
    height: '100%',
    padding: 10,
    width: 260,
  },
  columnHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  columnTitle: { fontSize: 16, fontWeight: '700' },
  columnCount: { fontSize: 13, fontWeight: '600' },
  taskCard: {
    position: 'relative',
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  taskTitle: { fontSize: 15, fontWeight: '700', paddingRight: 22 },
  taskDescription: { fontSize: 13, lineHeight: 18, marginTop: 7 },
  taskDetail: { flexShrink: 1, fontSize: 12, marginTop: 7 },
  holdFeedback: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
    borderRadius: 10,
    bottom: 0,
    justifyContent: 'flex-end',
    left: 0,
    paddingBottom: 10,
    paddingHorizontal: 12,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  holdTrack: { borderRadius: 3, height: 5, overflow: 'hidden', width: '100%' },
  holdProgress: { height: 5 },
  hiddenTaskCard: { opacity: 0 },
  dragOverlay: {
    elevation: 100,
    left: 0,
    position: 'absolute',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    top: 0,
    zIndex: 100,
  },
  emptyColumn: { fontSize: 13, paddingVertical: 18, textAlign: 'center' },
  state: { alignItems: 'center', paddingVertical: 48 },
  stateCard: { borderRadius: 12, borderWidth: 1, margin: 20, padding: 20 },
  stateTitle: { fontSize: 17, fontWeight: '700', textAlign: 'center' },
  stateText: { fontSize: 14, marginTop: 10, textAlign: 'center' },
  tasksButton: {
    alignItems: 'center',
    borderRadius: 7,
    borderWidth: 1,
    marginTop: 9,
    paddingVertical: 7,
  },
  tasksButtonText: { fontSize: 12, fontWeight: '700' },
  columnScroll: { flex: 1 },
  menuButton: {
    alignItems: 'center',
    height: 26,
    justifyContent: 'center',
    position: 'absolute',
    right: 5,
    top: 4,
    width: 26,
    zIndex: 1,
  },
  menuText: { fontSize: 20, fontWeight: '700', lineHeight: 20 },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: { borderRadius: 14, padding: 20, width: '100%' },
  modalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 14 },
  memberButton: { borderRadius: 8, borderWidth: 1, marginTop: 8, padding: 12 },
  closeButton: { alignItems: 'flex-end', marginTop: 14 },
  actionLoading: {
    alignItems: 'center',
    bottom: 18,
    left: 0,
    position: 'absolute',
    right: 0,
  },
});
