import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: { flex: 1 },
  projectTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginHorizontal: 20,
    marginTop: 18,
  },
  board: {
    gap: 12,
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  boardScroll: { flex: 1 },
  column: {
    borderRadius: 12,
    borderWidth: 1,
    height: '100%',
    padding: 10,
    width: 260,
  },
  columnHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  columnTitle: { fontSize: 16, fontWeight: '700' },
  columnCount: { fontSize: 13, fontWeight: '600' },
  taskCard: {
    position: 'relative',
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  taskTitle: { fontSize: 15, fontWeight: '700', paddingRight: 22 },
  taskDescription: { fontSize: 13, lineHeight: 18, marginTop: 7 },
  taskDetail: { flexShrink: 1, fontSize: 12, marginTop: 7 },
  emptyColumn: { fontSize: 13, paddingVertical: 18, textAlign: 'center' },
  state: { alignItems: 'center', paddingVertical: 48 },
  stateCard: { borderRadius: 12, borderWidth: 1, margin: 20, padding: 20 },
  stateTitle: { fontSize: 17, fontWeight: '700', textAlign: 'center' },
  stateText: { fontSize: 14, marginTop: 10, textAlign: 'center' },
  tasksButton: {
    alignItems: 'center',
    borderRadius: 7,
    borderWidth: 1,
    marginTop: 9,
    paddingVertical: 7,
  },
  tasksButtonText: { fontSize: 12, fontWeight: '700' },
  columnScroll: { flex: 1 },
  menuButton: {
    alignItems: 'center',
    height: 26,
    justifyContent: 'center',
    left: 5,
    position: 'absolute',
    top: 4,
    width: 26,
    zIndex: 1,
  },
  menuText: { fontSize: 20, fontWeight: '700', lineHeight: 20 },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: { borderRadius: 14, padding: 20, width: '100%' },
  modalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 14 },
  memberButton: { borderRadius: 8, borderWidth: 1, marginTop: 8, padding: 12 },
  closeButton: { alignItems: 'flex-end', marginTop: 14 },
  actionLoading: {
    alignItems: 'center',
    bottom: 18,
    left: 0,
    position: 'absolute',
    right: 0,
  },
});
